/* eslint-disable import/no-unresolved */
import {
  PUSHER_APP_ID,
  GOOGLE_AND,
  GOOGLE_IOS,
  DIALOG_FLOW_CLIENT_EMAIL,
  DIALOG_FLOW_PROJECT_ID,
  BASE_URL,
  DIALOG_FLOW_PRIVATE_KEY,
  OCR,
} from '@env';

export default {
  PUSHER_APP_ID,
  GOOGLE_IOS,
  DIALOG_FLOW_CLIENT_EMAIL,
  GOOGLE_AND,
  DIALOG_FLOW_PRIVATE_KEY,
  BASE_URL,
  OCR,
  DIALOG_FLOW_PROJECT_ID,
};
