/* eslint-disable import/no-unresolved */
import {
  PUSHER_APP_ID, GOOGLE_IOS, GOOGLE_ANDROID,
  DIALOG_FLOW_CLIENT_EMAIL, DIALOG_FLOW_PRIVATE_KEY, DIALOG_FLOW_PROJECT_ID,
} from '@env';

export default {
  PUSHER_APP_ID,
  GOOGLE_IOS,
  GOOGLE_ANDROID,
  DIALOG_FLOW_CLIENT_EMAIL,
  DIALOG_FLOW_PRIVATE_KEY,
  DIALOG_FLOW_PROJECT_ID,
};
