/* eslint-disable import/no-unresolved */
import {
  PUSHER_APP_ID,
  PUSHER_KEY,
  PUSHER_SECRET,
  PUSHER_CLUSTER,
  GOOGLE_AND,
  GOOGLE_IOS,
  DIALOG_FLOW_CLIENT_EMAIL,
  DIALOG_FLOW_PRIVATE_KEY,
  DIALOG_FLOW_PROJECT_ID,
  BASE_URL,
  OCR,
} from '@env';

export default {
  PUSHER_APP_ID,
  PUSHER_KEY,
  PUSHER_SECRET,
  PUSHER_CLUSTER,
  GOOGLE_IOS,
  DIALOG_FLOW_CLIENT_EMAIL,
  GOOGLE_AND,
  DIALOG_FLOW_PRIVATE_KEY,
  DIALOG_FLOW_PROJECT_ID,
  BASE_URL,
  OCR,
};

module.exports = {
  s3: {
    pusher: process.env.PUSHER_APP_ID,
  },
};
